name: Bug Report
description: File a bug report.
title: '[bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        ## Please help us help you!

        Before filing your issue, ask yourself:
        - Is there an issue already opened for this bug?
        - Can I reproduce it?
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Write down the steps to reproduce the bug, please include any information that seems relevant for us to reproduce it properly
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. You can set `debug = true` in your neovim-plugin-boilerplate config and then use `:message<CR>` in order to see the logs.
      render: shell
  - type: checkboxes
    attributes:
      label: Self-service
      description: |
        If you feel like you could contribute to this issue, please check the box below. This would tell us and other people looking for contributions that someone's working on it.
      options:
        - label: I'd be willing to fix this bug myself.

